"""Update daily_productions with new fields and unique constraint

Revision ID: 8d07d9d2ce2b
Revises: aac9f899be99
Create Date: 2026-06-08 14:09:48.408850

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d07d9d2ce2b"
down_revision: Union[str, Sequence[str], None] = "aac9f899be99"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_productions",
        sa.Column("working_hours", sa.Float(), nullable=True, server_default="24"),
    )
    op.add_column(
        "daily_productions",
        sa.Column("liquid_volume", sa.Float(), nullable=True, server_default="0"),
    )
    op.add_column(
        "daily_productions",
        sa.Column("water_cut", sa.Float(), nullable=True, server_default="0"),
    )
    op.add_column(
        "daily_productions",
        sa.Column("density", sa.Float(), nullable=True, server_default="0.86"),
    )
    op.create_unique_constraint(
        "uq_well_date", "daily_productions", ["well_id", "date"]
    )
    op.drop_column("daily_productions", "oil_volume")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_productions",
        sa.Column(
            "oil_volume",
            sa.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_well_date", "daily_productions", type_="unique")
    op.drop_column("daily_productions", "density")
    op.drop_column("daily_productions", "water_cut")
    op.drop_column("daily_productions", "liquid_volume")
    op.drop_column("daily_productions", "working_hours")
    # ### end Alembic commands ###
