"""Add daily_productions table

Revision ID: aac9f899be99
Revises: fd87fd6021e1
Create Date: 2026-05-28 10:37:49.271518

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aac9f899be99'
down_revision: Union[str, Sequence[str], None] = 'fd87fd6021e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_productions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('well_id', sa.Integer(), nullable=False),
    sa.Column('oil_volume', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['well_id'], ['wells.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_productions_id'), 'daily_productions', ['id'], unique=False)
    op.alter_column('oil_companies', 'region',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('oil_companies', 'region',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_daily_productions_id'), table_name='daily_productions')
    op.drop_table('daily_productions')
    # ### end Alembic commands ###
