"""Initial migration

Revision ID: fd87fd6021e1
Revises:
Create Date: 2026-05-25 16:20:47.639459

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fd87fd6021e1"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oil_companies",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("region", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_oil_companies_id"), "oil_companies", ["id"], unique=False)
    op.create_table(
        "employees",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column("position", sa.String(), nullable=True),
        sa.Column("password", sa.String(), nullable=False),
        sa.Column("oil_company_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["oil_company_id"],
            ["oil_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index(op.f("ix_employees_id"), "employees", ["id"], unique=False)
    op.create_table(
        "wells",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("max_drilling_depth", sa.Integer(), nullable=False),
        sa.Column("oil_company_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["oil_company_id"],
            ["oil_companies.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_wells_id"), "wells", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wells_id"), table_name="wells")
    op.drop_table("wells")
    op.drop_index(op.f("ix_employees_id"), table_name="employees")
    op.drop_table("employees")
    op.drop_index(op.f("ix_oil_companies_id"), table_name="oil_companies")
    op.drop_table("oil_companies")
    # ### end Alembic commands ###
